ausy_event.settings:
  type: config_object
  label: 'Ausy Event Settings'
  mapping:
    departments:
      type: sequence
      label: 'Departments'
      sequence:
        - type: ausy_event_department.[%key]

ausy_event_department.*:
  type: string
  label: 'Department'
